/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-02-15

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

#include "rs485.h"
#include "ain.h"
#include "din.h"
#include "dout.h"
#include "watchdog.h"
#include "settings.h"
#include "pcf8575.h"

/* Private typedef */
/* Private define  */

#define MC3550				0
#define MC3551				1
#define MC3552				2
#define MC3553				3
#define MC3554				4
#define MC3555				5
#define MC3556				6
#define MC3557				7
#define MC3558				8
#define MC3559				9

#define Main_TASK_PRIORITY              ( tskIDLE_PRIORITY + 1 )
#define Main_DELAY						( ( portTickType ) 1000 / portTICK_RATE_MS )

/* Private macro */
/* Private variables */

unsigned char typeOfDevice = MC3554;

/* Private function prototypes */
/* Private functions */

static void MainTask( void *pvParameters )
{
	portTickType xLastExecutionTime;
    xLastExecutionTime = xTaskGetTickCount();

    // LED init
    GPIO_InitTypeDef GPIO_InitStructure;
	RCC_APB2PeriphClockCmd( RCC_APB2Periph_GPIOA, ENABLE );
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_1 | GPIO_Pin_0;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init( GPIOA, &GPIO_InitStructure );

    for( ;; )
	{
        GPIOA->ODR ^= GPIO_Pin_1;	 // RUN LED
        vTaskDelayUntil( &xLastExecutionTime, Main_DELAY );
        IWDG_ReloadCounter();
    }
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  init_settings_memory(7);
  xTaskCreate( MainTask, ( const char * ) "Main", configMINIMAL_STACK_SIZE, NULL, Main_TASK_PRIORITY, NULL );
  xTaskCreate( rs485Task, ( const char * ) "RS485", configMINIMAL_STACK_SIZE, NULL, RS485_TASK_PRIORITY, NULL );
  switch(typeOfDevice) {
	  case MC3550:
		  set_di16_inp_reg_addr(0);
		  xTaskCreate( din16Task, ( const char * ) "DIN16", configMINIMAL_STACK_SIZE, NULL, DIN_TASK_PRIORITY, NULL );
		  break;
	  case MC3551:
		  set_do16_hold_reg_addr(0);
		  xTaskCreate( dout16Task, ( const char * ) "DOUT16", configMINIMAL_STACK_SIZE, NULL, DOUT_TASK_PRIORITY, NULL );
		  break;
	  case MC3552:
		  set_di8_inp_reg_addr(0);
		  set_do8_hold_reg_addr(0);
		  set_di8_set(0);
		  xTaskCreate( din8Task, ( const char * ) "DIN8", configMINIMAL_STACK_SIZE, NULL, DOUT_TASK_PRIORITY, NULL );
		  xTaskCreate( dout8Task, ( const char * ) "DOUT8", configMINIMAL_STACK_SIZE, NULL, DOUT_TASK_PRIORITY, NULL );
		  break;
	  case MC3553:
		  set_di8_inp_reg_addr(16);
		  set_di8_set(1);
		  xTaskCreate( din8Task, ( const char * ) "DIN8", configMINIMAL_STACK_SIZE, NULL, DOUT_TASK_PRIORITY, NULL );
		  xTaskCreate( ain8Task, ( const char * ) "AIN8", configMINIMAL_STACK_SIZE*2, NULL, AIN_TASK_PRIORITY, NULL );
		  break;
	  case MC3554:
		  set_do8_hold_reg_addr(0);
		  xTaskCreate( dout8Task, ( const char * ) "DOUT8", configMINIMAL_STACK_SIZE, NULL, DOUT_TASK_PRIORITY, NULL );
		  xTaskCreate( ain8Task, ( const char * ) "AIN8", configMINIMAL_STACK_SIZE*2, NULL, AIN_TASK_PRIORITY, NULL );
		  break;
	  case MC3555:
		  set_do8_hold_reg_addr(0);
		  xTaskCreate( dout8Task, ( const char * ) "DOUT8", configMINIMAL_STACK_SIZE, NULL, DOUT_TASK_PRIORITY, NULL );
		  break;
  	  case MC3556:
  		  xTaskCreate( ain16Task, ( const char * ) "AIN16", configMINIMAL_STACK_SIZE*2, NULL, AIN_TASK_PRIORITY, NULL );
  		  break;
  	  case MC3559:
  		  xTaskCreate( ain8Task, ( const char * ) "AIN8", configMINIMAL_STACK_SIZE*2, NULL, AIN_TASK_PRIORITY, NULL );
  		  break;
  }

  xTaskCreate(pcf8575Task, (const char *) "PCF8575", configMINIMAL_STACK_SIZE, NULL, PCF8575_TASK_PRIORITY, NULL);
  /* TODO - Add your application code here */
  iwdg_init();
  vTaskStartScheduler();
  /* Infinite loop */
  while (1) {}
}


